export const types = {
  FILTERS_ADD_COUNTRY: 'FILTERS_ADD_COUNTRY',
  FILTERS_REMOVE_COUNTRY: 'FILTERS_REMOVE_COUNTRY',
  FILTERS_SET_COUNTRY_FILTER: 'FILTERS_SET_COUNTRY_FILTER',
  TIME_SERIES_FETCH: 'TIME_SERIES_FETCH',
  TIME_SERIES_FETCH_SUCCESS: 'TIME_SERIES_FETCH_SUCCESS',
  TIME_SERIES_RESET_REDUCER: 'TIME_SERIES_RESET_REDUCER',
}

export default types
