export const types = {
  CHART_SET_AGG_TYPE: 'CHART_SET_AGG_TYPE',
  CHART_SET_CHART_TYPE: 'CHART_SET_CHART_TYPE',
  CHART_SET_SCALE_TYPE: 'CHART_SET_SCALE_TYPE',
  TIME_SERIES_FETCH: 'TIME_SERIES_FETCH',
  TIME_SERIES_FETCH_SUCCESS: 'TIME_SERIES_FETCH_SUCCESS',
  TIME_SERIES_FETCH_ERROR: 'TIME_SERIES_FETCH_ERROR',
  TIME_SERIES_RESET_REDUCER: 'TIME_SERIES_RESET_REDUCER',
}

export default types
