export const types = {
  TIME_SERIES_FETCH: 'TIME_SERIES_FETCH',
  TIME_SERIES_FETCH_SUCCESS: 'TIME_SERIES_FETCH_SUCCESS',
  TIME_SERIES_RESET_REDUCER: 'TIME_SERIES_RESET_REDUCER',
}

export default types
