# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: yarn
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: yarn build
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: yarn test
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp.kokokoding.nl/domains/kokokoding.nl/public_html/kovid-19
        ftp-username: ${{ secrets.FtpUser }}
        ftp-password: ${{ secrets.FtpPassword }}
        local-dir: /build
      env:
        CI: true
