name: CI - Update COVID-19 Data

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: CSSEGISandData/COVID-19
          path: public/COVID-19
      - name: dist-to-ft
        uses: isthatcentered/dist-to-ftp@v1
        with:
          host: kokokoding.nl
          user: ${{ secrets.FtpUser }}
          password: ${{ secrets.FtpPassword }}
          path: ./public/COVID-19
          into: /domains/kokokoding.nl/public_html/kovid-19/COVID-19
        env:
          CI: true
