# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: dist-to-ft
        uses: isthatcentered/dist-to-ftp@v1
        with:
          host: kokokoding.nl
          user: ${{ secrets.FtpUser }}
          password: ${{ secrets.FtpPassword }}
          path: ./public/COVID-19
          into: /domains/kokokoding.nl/public_html/kovid-19/COVID-19
        env:
          CI: true
