# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Fast FTP Deploy
        uses: swznd/ftp-deploy@v1.0.1
        with:
          host: kokokoding.nl
          user: ${{ secrets.FtpUser }}
          password: ${{ secrets.FtpPassword }}
          local_path: /public/Covid-19
          remote_path: /domains/kokokoding.nl/public_html/kovid-19/COVID-19
        env:
          CI: true
